Abort pull if a repository is not on its master branch.

diff --git a/repotool b/repotool
--- a/repotool
+++ b/repotool
@@ -92,10 +92,15 @@ case "$CMD" in
         git clone $BASE_URL$n$SUFFIX
       else
         ( cd $n
-          emphasize "PULL $n"
-          if ! git pull $BASE_URL$n$SUFFIX $BRANCH ; then
-            emphasize "PULL IN $n FAILED" 
+          if test "$(git status | head -n 1)" != "# On branch master"; then
+            emphasize "$n NOT ON MASTER BRANCH -- ABORTING"
             exit 1
+          else
+            emphasize "PULL $n"
+            ##if ! git pull $BASE_URL$n$SUFFIX $BRANCH ; then
+              #emphasize "PULL IN $n FAILED" 
+              #exit 1
+            #fi
           fi
         ) || exit 1
       fi
